### ISSUE TITLE
On mobile messages only show the username and text section `[]()`

### ISSUE THREAD

**Issue by mikeytown2** [JoeBanks13/webhook-discord#12]
Could each method have a text parameter so this can be changed?

**Comment by JoeBanks13** [comment]
Could you send a screenshot and some code samples showing what you mean? I'm running iOS 11, Discord TestFlight v2.3.1 build no. 4051 and I don't see this.

**Comment by JoeBanks13** [comment]
Just had a friend test this on Android as well, they see nothing

![image](https://user-images.githubusercontent.com/20439493/39770010-bc246fd8-52e5-11e8-9a03-e52f79538b45.png)

**Comment by mikeytown2** [comment]
Also on IOS 11.3.1. It's happens on the lock screen. In the app it is correct.

**Comment by JoeBanks13** [comment]
That's more of a Discord issue than an issue with this. If you want it could be brought up at [Discord Testers](https://discord.gg/discord-testers) but there isn't really anything that needs changing around this.

**Comment by mikeytown2** [comment]
Is '[]()' a hard requirement to get the fancy formatted messages?

**Comment by JoeBanks13** [comment]
Hmm, testing locally it looks like it works without the `[]()`. I think this has changed. I'll remove all these in the next version (which will have your #14 issue fixed as well)
