### ISSUE TITLE
If user name contains a emoji like :warning: then it fails

### ISSUE THREAD

**Issue by mikeytown2** [JoeBanks13/webhook-discord#13]
`UnhandledPromiseRejectionWarning: {"webhook": ["username"]}
    at emitWarning (internal/process/promises.js:67:17)
    at emitPendingUnhandledRejections (internal/process/promises.js:109:11)
    at process._tickCallback (internal/process/next_tick.js:189:7)
`

**Comment by mikeytown2** [comment]
Also long username will also fail. Graceful handling of the username issues would be helpful

**Comment by JoeBanks13** [comment]
If you want an emoji in the name then use the unicode, colon emojis are not supported by Discord.

**Comment by JoeBanks13** [comment]
Typing `\:emoji_name:` in Discord can get you the unicode value of the emoji.

**Comment by JoeBanks13** [comment]
Username length verification has been added in 2.3.0

**Comment by mikeytown2** [comment]
Thanks for adding this in!
