### ISSUE TITLE
Blank Embeds on Message Without Attachments 

### ISSUE THREAD

**Issue by c-wolfe** [JoeBanks13/webhook-discord#23]
When sending a message that doesn't contain a color, field, timestamp, etc, the message is displayed with a blank embed object.

**Comment by jos-b** [comment]
Is this not intentional? You can't send an empty message anyway...

**Comment by imblakelol** [comment]
Not an empty message, a plain text message. If you send a message without an embed, it still has a blank embed object.

![screenshot](https://i.imgur.com/xxyo1HK.png "screenshot")

**Comment by jos-b** [comment]
Right that makes more sense, in that case let's discuss on the PR how to get it to not cause promise exceptions and then I'm happy with this change.
