### ISSUE TITLE
Build failed status and causes bot to crash on this latest update

### ISSUE THREAD

**Issue by BannerBomb** [JoeBanks13/webhook-discord#7]
this packages shows `Build Failing` and it crashes my discord bot ever since this last update
![image](https://user-images.githubusercontent.com/11788894/37851809-aa078c70-2eb6-11e8-9bfd-bea8a24e5080.png)

**Comment by JoeBanks13** [comment]
This is due to the fact that I removed all travis related files because I got bored of testing this when it's not a huge library. I'll remove the shield for now as travis is unused.
